services:
  db:
    image: postgres:15-alpine
    container_name: p1_backend

    # Restart PostgreSQL automatically after a VM or Docker restart.
    restart: unless-stopped

    # Read database credentials from the .env file.
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    # Persist PostgreSQL data.
    volumes:
      - pgdata:/var/lib/postgresql/data

    # Wait until PostgreSQL is ready.
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - project1-network

  web:
    # Build locally when using docker compose up --build
    build:
      context: .
      dockerfile: Dockerfile

    # Tag the image with your Docker Hub repository
    image: henokabebe/project1-api:latest

    container_name: p1_web_api

    restart: unless-stopped

    ports:
      - "8080:8080"

    # Load secrets
    env_file:
      - .env

    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      db:
        condition: service_healthy

    networks:
      - project1-network

  # Prometheus monitoring service
  prometheus:
    image: prom/prometheus:latest

    # Name of the Prometheus container
    container_name: p1_prometheus

    # Restart automatically if the VM or Docker restarts
    restart: unless-stopped

    # Expose Prometheus Web UI
    ports:
      - "9090:9090"

    # Mount the local configuration file into the container
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    # Start Prometheus using the mounted configuration file
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

    # Connect Prometheus to the same Docker network as FastAPI
    networks:
      - project1-network

    # Start after the FastAPI container
    depends_on:
      - web

volumes:
  pgdata:

networks:
  project1-network:
    driver: bridge